reminder:
    time: "17:00"
    title: Default title
    message: Default message
plugins:
    jira:
        enabled: false
        base_url: ""
    github:
        enabled: false
        api_token: ""
